=== nalleta/sewV3/xml/circuito.dtd
<!ELEMENT circuitos (circuito+)>
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, fuente*, fotografia+, video*, coordenadas, tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT fuente (#PCDATA)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas)>
<!ELEMENT distancia (#PCDATA)>

<!ATTLIST longitud kilometros CDATA #REQUIRED>
<!ATTLIST anchura metros CDATA #REQUIRED>
<!ATTLIST distancia 
    metros CDATA #REQUIRED
    kilometros CDATA #IMPLIED>
<!ATTLIST tramo numero CDATA #REQUIRED>
<!ATTLIST coordenadas
     longitud CDATA #REQUIRED
     latitud CDATA #REQUIRED
     altitud CDATA #REQUIRED>

=== nalleta/sewV3/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitos SYSTEM "circuito.dtd">
<circuitos>
    <circuito>
        <nombre>Albert Park</nombre>
        <longitud kilometros="5,303"></longitud>
        <anchura metros="15"></anchura>
        <fecha>24/03/2024</fecha>
        <hora>4:30</hora>
        <vueltas>58</vueltas>
        <localidad>Melbourne</localidad>
        <pais>Australia</pais>
        <fuente>https://www.motorpasion.com/formula1/analisis-tecnico-del-circuito-de-albert-park-melbourne</fuente>
        <fuente>https://es.wikipedia.org/wiki/Circuito_de_Albert_Park</fuente>
        <fuente>https://www.redbull.com/es-es/plano-del-trazado-de-albert-park-melbourne</fuente>
        <fuente>https://www.formula1.com/en/racing/2024/australia</fuente>
        <fuente>https://www.dazn.com/es-ES/news/motor/circuito-de-albert-park-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-australia-del-mundial-de-f1/l72phjxopbx61bsz5jkudezvy</fuente>
        <fotografia>AlbertPark.jpg</fotografia>
        <fotografia>AlbertParkEsquematizado.png</fotografia>
        <fotografia>AlbertParkArriba.jpg</fotografia>
        <video>AlbertPark.mp4</video>
        <coordenadas latitud="-37,8500761" longitud="144,9689996" altitud="4,898"></coordenadas>
        <tramos>
            <tramo numero="1">
                <distancia metros="381,11"></distancia>
                <coordenadas latitud="-37,8475972" longitud="144,9660005" altitud="4,125895"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia metros="9,32"></distancia>
                <coordenadas latitud="-37,8467394" longitud="144,9662229" altitud="4,428"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia metros="616,81"></distancia>
                <coordenadas latitud="-37,8422066" longitud="144,9621462" altitud="4,6803"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia metros="146,46"></distancia>
                <coordenadas latitud="-37,8417953" longitud="144,9637148" altitud="4.686"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia metros="217,93"></distancia>
                <coordenadas latitud="-37,8398564" longitud="144,9637168" altitud="5,5496"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="422,26"></distancia>
                <coordenadas latitud="-37,8380550" longitud="144,9678925" altitud="4,54748"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="138,73"></distancia>
                <coordenadas latitud="-37,8384531" longitud="144,9693757" altitud="1,04765"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="216,68"></distancia>
                <coordenadas latitud="-37,8396853" longitud="144,9713322" altitud="0,610757"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="220,43"></distancia>
                <coordenadas latitud="-37,8416460" longitud="144,9717477" altitud="5,3557002"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="343,87"></distancia>
                <coordenadas latitud="-37,8445734" longitud="144,9705818" altitud="1,3964248"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia metros="274,27"></distancia>
                <coordenadas latitud="-37,8469014" longitud="144,9715911" altitud="1,0479151"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="209,76"></distancia>
                <coordenadas latitud="-37,8480928" longitud="144,9734176" altitud="5,1056796"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="120,67"></distancia>
                <coordenadas latitud="-37,8481040" longitud="144,9747817" altitud="5,1938677"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="294,34"></distancia>
                <coordenadas latitud="-37,8498499" longitud="144,9772939" altitud="5,7381754"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="410,96"></distancia>
                <coordenadas latitud="-37,8533880" longitud="144,9786139" altitud="6,0217242"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="255,43"></distancia>
                <coordenadas latitud="-37,8539085" longitud="144,9757788" altitud="4,7670262"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="245,39"></distancia>
                <coordenadas latitud="-37,8520983" longitud="144,9741073" altitud="4,7375816"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="145,76"></distancia>
                <coordenadas latitud="-37,8528808" longitud="144,9727597" altitud="4,4096870"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia metros="456,81"></distancia>
                <coordenadas latitud="-37,8500634" longitud="144,9689850" altitud="4,8980248"></coordenadas>
            </tramo>
        </tramos>
    </circuito>
</circuitos>
