=== nalleta/sewV3/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="fuente" />
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
				<xs:element ref="coordenadas" />
				<xs:element ref = "tramos"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="double_positivo_type">
					<xs:attribute name="magnitud" type="magnitudes" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="double_positivo_type">
					<xs:attribute name="magnitud" type="magnitudes" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="fuente" type="xs:string" />
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="video" type="xs:string" />
	
	<xs:simpleType name ="longitud_type">
		<xs:restriction base="xs:double">
			<xs:minInclusive value ="-180"/>
			<xs:maxInclusive value ="180"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name ="latitud_type">
		<xs:restriction base="xs:double">
			<xs:minInclusive value ="-90"/>
			<xs:maxInclusive value ="90"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name ="double_positivo_type">
		<xs:restriction base="xs:double">
			<xs:minInclusive value ="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name ="magnitudes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="metros"/>
			<xs:enumeration value="kilÃ³metros"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud" type="longitud_type" use="required" />
					<xs:attribute name="latitud" type="latitud_type" use="required" />
					<xs:attribute name="altitud" type="double_positivo_type" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="numero" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="double_positivo_type">
					<xs:attribute name="magnitud" type="magnitudes" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nalleta/sewV3/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitos>
<circuitos
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <circuito>
        <nombre>Albert Park</nombre>
        <longitud magnitud="kilÃ³metros">5.303</longitud>
        <anchura magnitud="metros">5.303</anchura>
        <fecha>2024-03-24</fecha>
        <hora>04:30:00</hora>
        <vueltas>58</vueltas>
        <localidad>Melbourne</localidad>
        <pais>Australia</pais>
        <fuente>https://www.motorpasion.com/formula1/analisis-tecnico-del-circuito-de-albert-park-melbourne</fuente>
        <fuente>https://es.wikipedia.org/wiki/Circuito_de_Albert_Park</fuente>
        <fuente>https://www.redbull.com/es-es/plano-del-trazado-de-albert-park-melbourne</fuente>
        <fuente>https://www.formula1.com/en/racing/2024/australia</fuente>
        <fuente>https://www.dazn.com/es-ES/news/motor/circuito-de-albert-park-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-australia-del-mundial-de-f1/l72phjxopbx61bsz5jkudezvy</fuente>
        <fotografia>multimedia/imagenes/AlbertPark.jpg</fotografia>
        <fotografia>multimedia/imagenes/CircuitoEsquematizado.png</fotografia>
        <fotografia>multimedia/imagenes/AlbertParkArriba.jpg</fotografia>   
        <video>multimedia/video/AlbertPark.mp4</video>
        <coordenadas latitud="-37.8500761" longitud="144.9689996" altitud="4.898"></coordenadas>
        <tramos>
            <tramo numero="1">
                <distancia magnitud="metros">381.11</distancia>
                <coordenadas latitud="-37.8475972" longitud="144.9660005" altitud="4.125895"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia magnitud="metros">9.32</distancia>
                <coordenadas latitud="-37.8467394" longitud="144.9662229" altitud="4.428"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia magnitud="metros">616.81</distancia>
                <coordenadas latitud="-37.8422066" longitud="144.9621462" altitud="4.6803"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia magnitud="metros">146.46</distancia>
                <coordenadas latitud="-37.8417953" longitud="144.9637148" altitud="4.686"></coordenadas>
            </tramo>
            <tramo numero="1">
                <distancia magnitud="metros">217.93</distancia>
                <coordenadas latitud="-37.8398564" longitud="144.9637168" altitud="5.5496"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">422.26</distancia>
                <coordenadas latitud="-37.8380550" longitud="144.9678925" altitud="4.54748"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">138.73</distancia>
                <coordenadas latitud="-37.8384531" longitud="144.9693757" altitud="1.04765"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">216.68</distancia>
                <coordenadas latitud="-37.8396853" longitud="144.9713322" altitud="0.610757"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">220.43</distancia>
                <coordenadas latitud="-37.8416460" longitud="144.9717477" altitud="5.3557002"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">343.87</distancia>
                <coordenadas latitud="-37.8445734" longitud="144.9705818" altitud="1.3964248"></coordenadas>
            </tramo>
            <tramo numero="2">
                <distancia magnitud="metros">274.27</distancia>
                <coordenadas latitud="-37.8469014" longitud="144.9715911" altitud="1.0479151"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">209.76</distancia>
                <coordenadas latitud="-37.8480928" longitud="144.9734176" altitud="5.1056796"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">120.67</distancia>
                <coordenadas latitud="-37.8481040" longitud="144.9747817" altitud="5.1938677"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">294.34</distancia>
                <coordenadas latitud="-37.8498499" longitud="144.9772939" altitud="5.7381754"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">410.96</distancia>
                <coordenadas latitud="-37.8533880" longitud="144.9786139" altitud="6.0217242"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">255.43</distancia>
                <coordenadas latitud="-37.8539085" longitud="144.9757788" altitud="4.7670262"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">245.39</distancia>
                <coordenadas latitud="-37.8520983" longitud="144.9741073" altitud="4.7375816"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">145.76</distancia>
                <coordenadas latitud="-37.8528808" longitud="144.9727597" altitud="4.4096870"></coordenadas>
            </tramo>
            <tramo numero="3">
                <distancia magnitud="metros">456.81</distancia>
                <coordenadas latitud="-37.8500634" longitud="144.9689850" altitud="4.8980248"></coordenadas>
            </tramo>
        </tramos>
    </circuito>
</circuitos>
